/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rps_game;

import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac Ogunleye
 */
public class GameScreen extends javax.swing.JFrame {

    private int questionCount;
    static int playerScore = 0;
    static int computerScore = 0;

    int human_choice;
    int computer_choice;

    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);

        playerlblscore.setText(Integer.toString(playerScore));
        complblscore.setText(Integer.toString(computerScore));
    }

    public ImageIcon resizeImage(String path, JLabel label) {
        ImageIcon icon1 = new ImageIcon(path);
        Image image = icon1.getImage();
        Image newImage = image.getScaledInstance(label.getWidth(), label.getHeight(),
                Image.SCALE_SMOOTH);

        ImageIcon newResized = new ImageIcon(newImage);
        return newResized;
    }

    public void computerLogic() {
        //Random rand = new Random();
        computer_choice = (int) (Math.random() * 3);
        switch (computer_choice) {
            case 0:
                computerIcon.setIcon(resizeImage("src/Game_Images/rockImg.jpg", computerIcon));
                System.out.println("computer choose rock");
                break;
            case 1:
                computerIcon.setIcon(resizeImage("src/Game_Images/paperImg.jpg", computerIcon));
                System.out.println("computer choose paper");
                break;
            case 2:
                computerIcon.setIcon(resizeImage("src/Game_Images/scissorsImg.jpg", computerIcon));
                System.out.println("computer choose scissors");
                break;

        }
    }

    public void checkWinner() {
        if (human_choice == computer_choice) {
            gameStatus.setText("TIE");
            winnerlbl.setText("TIE!");
        } // scenerio for player beating computer
        else if (human_choice == 0 && computer_choice == 2) {// rock beats scissors
            gameStatus.setText("Player wins");
            winnerlbl.setText("Rock beats Scissors");
            playerScore++;
            playerlblscore.setText(Integer.toString(playerScore));
        } else if (human_choice == 1 && computer_choice == 0) {// paper beats rock
            gameStatus.setText("Player wins");
            winnerlbl.setText("Paper beats Rock");
            playerScore++;
            playerlblscore.setText(Integer.toString(playerScore));
        } else if (human_choice == 2 && computer_choice == 1) {// scissors beats paper
            gameStatus.setText("Player wins");
            winnerlbl.setText("Scissors beats Paper");
            playerScore++;
            playerlblscore.setText(Integer.toString(playerScore));
        } //scenerio for computer beating player
        else if (computer_choice == 0 && human_choice == 2) {// rock beats scissors
            gameStatus.setText("Computer wins");
            winnerlbl.setText("Rock beats Scissors");
            computerScore++;
            complblscore.setText(Integer.toString(computerScore));
        } else if (computer_choice == 1 && human_choice == 0) {// paper beats rock
            gameStatus.setText("Computer wins");
            winnerlbl.setText("Paper beats Rock");
            computerScore++;
            complblscore.setText(Integer.toString(computerScore));
        } else if (computer_choice == 2 && human_choice == 1) {// scissors beats rock
            gameStatus.setText("Computer wins");
            winnerlbl.setText("Scissors beats Paper");
            computerScore++;
            complblscore.setText(Integer.toString(computerScore));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playerlbl = new javax.swing.JLabel();
        playerlbl1 = new javax.swing.JLabel();
        rockBtn = new javax.swing.JButton();
        paperBtn = new javax.swing.JButton();
        scissorsBtn = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        computerIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playerlblscore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        complblscore = new javax.swing.JLabel();
        gameStatus = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        minimizelbl = new javax.swing.JLabel();
        shutdownlbl = new javax.swing.JLabel();
        winnerlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(41, 125, 73));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        playerlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playerlbl.setForeground(new java.awt.Color(255, 255, 255));
        playerlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerlbl.setText("PLAYER ");

        playerlbl1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playerlbl1.setForeground(new java.awt.Color(255, 255, 255));
        playerlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerlbl1.setText("COMPUTER");

        rockBtn.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        rockBtn.setForeground(new java.awt.Color(0, 0, 0));
        rockBtn.setText("ROCK");
        rockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockBtnActionPerformed(evt);
            }
        });

        paperBtn.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        paperBtn.setForeground(new java.awt.Color(0, 0, 0));
        paperBtn.setText("PAPER");
        paperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperBtnActionPerformed(evt);
            }
        });

        scissorsBtn.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        scissorsBtn.setForeground(new java.awt.Color(0, 0, 0));
        scissorsBtn.setText("SCISSORS");
        scissorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Samsung Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCORE :");

        playerlblscore.setBackground(new java.awt.Color(255, 255, 255));
        playerlblscore.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        playerlblscore.setForeground(new java.awt.Color(255, 255, 255));
        playerlblscore.setToolTipText("player score");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Samsung Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SCORE :");

        complblscore.setBackground(new java.awt.Color(255, 255, 255));
        complblscore.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        complblscore.setForeground(new java.awt.Color(255, 255, 255));
        complblscore.setToolTipText("Computer score");

        gameStatus.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        gameStatus.setForeground(new java.awt.Color(255, 255, 255));
        gameStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resetBtn.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetBtn.setText("RESET GAME");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Game Count:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");

        minimizelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game_Images/icons8_Minimize_Window_48px.png"))); // NOI18N
        minimizelbl.setToolTipText("minimize");
        minimizelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelblMouseClicked(evt);
            }
        });

        shutdownlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game_Images/icons8_Close_Window_48px.png"))); // NOI18N
        shutdownlbl.setToolTipText("exit game to go back to homepage?");
        shutdownlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutdownlblMouseClicked(evt);
            }
        });

        winnerlbl.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        winnerlbl.setForeground(new java.awt.Color(255, 255, 255));
        winnerlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerlblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(rockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(playerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(winnerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(complblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(computerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(minimizelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shutdownlbl)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playerlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(scissorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shutdownlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scissorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(computerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(winnerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(playerlblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(complblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelblMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelblMouseClicked

    private void shutdownlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownlblMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Do you want to exit game and go to home screen?", "Prompt", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            HomePage_Game hpg = new HomePage_Game();
            dispose();
        }
    }//GEN-LAST:event_shutdownlblMouseClicked

    private void rockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockBtnActionPerformed
        // TODO add your handling code here:
        userIcon.setIcon(resizeImage("src/Game_Images/rockImg.jpg", userIcon));
        human_choice = 0;
        computerLogic();
        checkWinner();
    }//GEN-LAST:event_rockBtnActionPerformed

    private void paperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperBtnActionPerformed
        // TODO add your handling code here:
        userIcon.setIcon(resizeImage("src/Game_Images/paperImg.jpg", userIcon));
        human_choice = 1;
        computerLogic();
        checkWinner();
    }//GEN-LAST:event_paperBtnActionPerformed

    private void scissorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsBtnActionPerformed
        // TODO add your handling code here:
        userIcon.setIcon(resizeImage("src/Game_Images/scissorsImg.jpg", userIcon));
        human_choice = 2;
        computerLogic();
        checkWinner();
    }//GEN-LAST:event_scissorsBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure u want to reset Game!!", "Prompt", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        //if user clicks yes
         if (res == JOptionPane.YES_OPTION){
        int resetScore = 0;
        // Set both score back to Zero
        playerlblscore.setText(Integer.toString(resetScore));
        complblscore.setText(Integer.toString(resetScore));

        //set both scores back to zero
        playerScore = 0;
        computerScore = 0;

        // set both icons back to null
        userIcon.setIcon(null);
        computerIcon.setIcon(null);

        // set game status label to empty or null
        gameStatus.setText("");

        //set Winner label status to empty or null
        winnerlbl.setText("");
         }
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel complblscore;
    private javax.swing.JLabel computerIcon;
    private javax.swing.JLabel gameStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizelbl;
    private javax.swing.JButton paperBtn;
    private javax.swing.JLabel playerlbl;
    private javax.swing.JLabel playerlbl1;
    private javax.swing.JLabel playerlblscore;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton rockBtn;
    private javax.swing.JButton scissorsBtn;
    private javax.swing.JLabel shutdownlbl;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel winnerlbl;
    // End of variables declaration//GEN-END:variables
}
